import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-[url('/bg-image.avif')] bg-cover bg-center min-h-dvh min-w-full flex">
      {children}
      <div className="absolute bottom-0 w-full pb-4 flex flex-row gap-2 justify-center text-background">
        <span className="font-bold">© 2025 AutoBudget</span>
        <Link href="/impressum">Impressum</Link>
        <Link href="/Datenschutz">Datenschutz</Link>
      </div>
    </div>
  );
}
